apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: {{ include "crsaitool.fullname" . }}
  labels:
    {{- include "crsaitool.labels" . | nindent 4 }}
spec:
  template:
    metadata:
      labels:
        {{- include "crsaitool.selectorLabels" . | nindent 8 }}
      annotations:
        autoscaling.knative.dev/min-scale: {{ .Values.knative.minScale | quote }}
        autoscaling.knative.dev/max-scale: {{ .Values.knative.maxScale | quote }}
        autoscaling.knative.dev/targetConcurrency: {{ .Values.knative.concurrencyLimit | quote }}
    spec:
      containerConcurrency: {{ .Values.knative.concurrencyLimit }}
      timeoutSeconds: {{ .Values.knative.timeoutSeconds }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: crsaitool
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.containerPort }}
              name: http1
          envFrom:
            - configMapRef:
                name: {{ include "crsaitool.fullname" . }}-config
            - secretRef:
                name: {{ include "crsaitool.fullname" . }}-secret
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.service.containerPort }}
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.service.containerPort }}
            initialDelaySeconds: 30
            periodSeconds: 15
